# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: funding_label.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'funding_label.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x66unding_label.proto\x12\x07\x66unding\"\x94\x01\n\x0bHorizonCols\x12\x13\n\x07max_fav\x18\x01 \x03(\x11\x42\x02\x10\x01\x12\x13\n\x07max_adv\x18\x02 \x03(\x11\x42\x02\x10\x01\x12\x14\n\x08thit_fav\x18\x03 \x03(\x11\x42\x02\x10\x01\x12\x14\n\x08thit_adv\x18\x04 \x03(\x11\x42\x02\x10\x01\x12\x13\n\x07ret_end\x18\x05 \x03(\x11\x42\x02\x10\x01\x12\x1a\n\x0en_bars_deficit\x18\x06 \x03(\x11\x42\x02\x10\x01\"\xd3\x01\n\nLabelChunk\x12\x0f\n\x07symbols\x18\x01 \x03(\t\x12\x0f\n\x07\x62\x61se_ms\x18\x02 \x01(\x04\x12\x10\n\x08step_min\x18\x03 \x01(\r\x12\r\n\x05scale\x18\x04 \x01(\r\x12\x11\n\trow_count\x18\x05 \x01(\r\x12\x10\n\x08horizons\x18\x06 \x03(\t\x12\x12\n\x06sym_id\x18\x07 \x03(\x11\x42\x02\x10\x01\x12\x11\n\x05t_idx\x18\x08 \x03(\x11\x42\x02\x10\x01\x12\x15\n\tnull_mask\x18\t \x03(\rB\x02\x10\x01\x12\x1f\n\x01h\x18\n \x03(\x0b\x32\x14.funding.HorizonColsBB\n-com.binance.chuyennd.ai_ml.features.export.pbB\x11\x46undingLabelProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'funding_label_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n-com.binance.chuyennd.ai_ml.features.export.pbB\021FundingLabelProto'
  _globals['_HORIZONCOLS'].fields_by_name['max_fav']._loaded_options = None
  _globals['_HORIZONCOLS'].fields_by_name['max_fav']._serialized_options = b'\020\001'
  _globals['_HORIZONCOLS'].fields_by_name['max_adv']._loaded_options = None
  _globals['_HORIZONCOLS'].fields_by_name['max_adv']._serialized_options = b'\020\001'
  _globals['_HORIZONCOLS'].fields_by_name['thit_fav']._loaded_options = None
  _globals['_HORIZONCOLS'].fields_by_name['thit_fav']._serialized_options = b'\020\001'
  _globals['_HORIZONCOLS'].fields_by_name['thit_adv']._loaded_options = None
  _globals['_HORIZONCOLS'].fields_by_name['thit_adv']._serialized_options = b'\020\001'
  _globals['_HORIZONCOLS'].fields_by_name['ret_end']._loaded_options = None
  _globals['_HORIZONCOLS'].fields_by_name['ret_end']._serialized_options = b'\020\001'
  _globals['_HORIZONCOLS'].fields_by_name['n_bars_deficit']._loaded_options = None
  _globals['_HORIZONCOLS'].fields_by_name['n_bars_deficit']._serialized_options = b'\020\001'
  _globals['_LABELCHUNK'].fields_by_name['sym_id']._loaded_options = None
  _globals['_LABELCHUNK'].fields_by_name['sym_id']._serialized_options = b'\020\001'
  _globals['_LABELCHUNK'].fields_by_name['t_idx']._loaded_options = None
  _globals['_LABELCHUNK'].fields_by_name['t_idx']._serialized_options = b'\020\001'
  _globals['_LABELCHUNK'].fields_by_name['null_mask']._loaded_options = None
  _globals['_LABELCHUNK'].fields_by_name['null_mask']._serialized_options = b'\020\001'
  _globals['_HORIZONCOLS']._serialized_start=33
  _globals['_HORIZONCOLS']._serialized_end=181
  _globals['_LABELCHUNK']._serialized_start=184
  _globals['_LABELCHUNK']._serialized_end=395
# @@protoc_insertion_point(module_scope)
