AEROSPIKE_HOST=103.157.218.242
AEROSPIKE_NAMESPACE=ticker
AEROSPIKE_PORT=3222
AEROSPIKE_HOST_226=103.157.218.226
AEROSPIKE_PORT_226=3222
AEROSPIKE_SET_NAME_FUNDING_PRED=funding_pred_1m_v4
AEROSPIKE_SET_NAME_PRED_40=pred_40_1m

RATE_FEE=0.001
RATE_PROFIT_STOP_MARKET=0.01

LEVERAGE_ORDER=1
NUMBER_ENTRY_EACH_SIGNAL=2
NUMBER_THREAD_ORDER_MANAGER=2
CAPITAL_START=35000
PROFIT_RATE=0.01
TIME_START=1714150800000
TIME_RUN=20210101

NUMBER_TICKER_CAL_RATE_CHANGE=15

BTC_TREND_REVERSE_DURATION=360
BTC_TREND_REVERSE_RATE_MAX=0.01
BTC_TREND_REVERSE_RATE_MIN=0.006
BTC_TREND_REVERSE_RATE_MIN_TRADE=0.0054

FILE_AI_PREDICTIONS=../storage/ai_ml/ai_predictions.data_v3_FULL
FILE_AI_DCA_PREDICTIONS=../storage/ai_ml_data/models_dca_strategy
FILE_ENTRY_MARKET_LEVEL=../storage/market_data_one_file/time2market.data


#20240320
DIED_SYMBOLS=STPTUSDT,SNTUSDT,MBLUSDT,RADUSDT,CVXUSDT,IDEXUSDT,SLPUSDT,GLMRUSDT,MDTUSDT,AUDIOUSDT,BLUEBIRDUSDT,FOOTBALLUSDT,ANTUSDT,CTKUSDT,DGBUSDT,STRAXUSDT,COCOSUSDT,RAYUSDT,FTTUSDT,SCUSDT,HNTUSDT,BTCSTUSDT,BTSUSDT,TOMOUSDT,SRMUSDT,CVCUSDT,USDCUSDT,BTCDOMUSDT,WAVESUSDT,BNXUSDT
SPECIAL_SYMBOLS=BNB,ETH,XRP,ADA
STABLE_SYMBOLS=SOL,ADA,DOGE,TRX,AVAX,LINK,XLM,VET,1000PEPE,SUI
#LINK,XLM,VET,1000PEPE,SUI,HBAR,1000SHIB,DOT,TON,BCH,LTC,UNI
#HBAR,1000SHIB,DOT,TON,BCH,LTC,UNI
BTC_REVERSE_SYMBOLS=ADA,AVAX,DOGE